name: CD
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/apps/go-basic-cicd
            git pull origin master
            git status
            CGO_ENABLE=0 GOOS=linux go build -a -installsuffix cgo -o main ./main.go
            pm2 restart main
